// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stringop.proto

package cmdpb // import "."

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StringOP struct {
	Op                   int32    `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"`
	Param                string   `protobuf:"bytes,2,opt,name=param,proto3" json:"param,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringOP) Reset()         { *m = StringOP{} }
func (m *StringOP) String() string { return proto.CompactTextString(m) }
func (*StringOP) ProtoMessage()    {}
func (*StringOP) Descriptor() ([]byte, []int) {
	return fileDescriptor_stringop_28e0e590f4390505, []int{0}
}
func (m *StringOP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringOP.Unmarshal(m, b)
}
func (m *StringOP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringOP.Marshal(b, m, deterministic)
}
func (dst *StringOP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringOP.Merge(dst, src)
}
func (m *StringOP) XXX_Size() int {
	return xxx_messageInfo_StringOP.Size(m)
}
func (m *StringOP) XXX_DiscardUnknown() {
	xxx_messageInfo_StringOP.DiscardUnknown(m)
}

var xxx_messageInfo_StringOP proto.InternalMessageInfo

func (m *StringOP) GetOp() int32 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *StringOP) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

func init() {
	proto.RegisterType((*StringOP)(nil), "StringOP")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StringopsrvClient is the client API for Stringopsrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StringopsrvClient interface {
	StringOpDo(ctx context.Context, in *StringOP, opts ...grpc.CallOption) (*DefaultResp, error)
}

type stringopsrvClient struct {
	cc *grpc.ClientConn
}

func NewStringopsrvClient(cc *grpc.ClientConn) StringopsrvClient {
	return &stringopsrvClient{cc}
}

func (c *stringopsrvClient) StringOpDo(ctx context.Context, in *StringOP, opts ...grpc.CallOption) (*DefaultResp, error) {
	out := new(DefaultResp)
	err := c.cc.Invoke(ctx, "/stringopsrv/StringOpDo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StringopsrvServer is the server API for Stringopsrv service.
type StringopsrvServer interface {
	StringOpDo(context.Context, *StringOP) (*DefaultResp, error)
}

func RegisterStringopsrvServer(s *grpc.Server, srv StringopsrvServer) {
	s.RegisterService(&_Stringopsrv_serviceDesc, srv)
}

func _Stringopsrv_StringOpDo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringOP)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StringopsrvServer).StringOpDo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stringopsrv/StringOpDo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StringopsrvServer).StringOpDo(ctx, req.(*StringOP))
	}
	return interceptor(ctx, in, info, handler)
}

var _Stringopsrv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stringopsrv",
	HandlerType: (*StringopsrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StringOpDo",
			Handler:    _Stringopsrv_StringOpDo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stringop.proto",
}

func init() { proto.RegisterFile("stringop.proto", fileDescriptor_stringop_28e0e590f4390505) }

var fileDescriptor_stringop_28e0e590f4390505 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x2e, 0x29, 0xca,
	0xcc, 0x4b, 0xcf, 0x2f, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0xe2, 0x4d, 0x49, 0x4d, 0x4b,
	0x2c, 0xcd, 0x29, 0x81, 0x70, 0x95, 0x0c, 0xb8, 0x38, 0x82, 0xc1, 0x0a, 0xfc, 0x03, 0x84, 0xf8,
	0xb8, 0x98, 0xf2, 0x0b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x98, 0xf2, 0x0b, 0x84, 0x44,
	0xb8, 0x58, 0x0b, 0x12, 0x8b, 0x12, 0x73, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c,
	0x23, 0x33, 0x2e, 0x6e, 0x98, 0x91, 0xc5, 0x45, 0x65, 0x42, 0xea, 0x5c, 0x5c, 0x50, 0x03, 0x0a,
	0x5c, 0xf2, 0x85, 0x38, 0xf5, 0x60, 0xa6, 0x49, 0xf1, 0xe8, 0xb9, 0x40, 0x6c, 0x0a, 0x4a, 0x2d,
	0x2e, 0x50, 0x62, 0x70, 0xe2, 0x8c, 0x62, 0xd7, 0xb3, 0x4e, 0xce, 0x4d, 0x29, 0x48, 0x4a, 0x62,
	0x03, 0xdb, 0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x33, 0xc2, 0x08, 0x42, 0x9c, 0x00, 0x00,
	0x00,
}
